### ISSUE TITLE
The secret of this module: wraps HTTP.[verb]

### ISSUE THREAD

**Issue by wizonesolutions** [percolatestudio/meteor-google-api#18]
Took me a while to figure this out; I was using a `POST` call to the Google Calendar API.

Most examples show `resource` being used in `options`, but with this package you have to do this:

````javascript
var newEvent = GoogleApi.post('/calendar/v3/calendars/' + calendarId + '/events', {
  data: resource
}
````

This is because `data` is how you get JSON data into a request body using `HTTP.post`. This package is just a wrapper for that which tacks on your Google auth and refreshes your OAuth token if necessary. And also lets you make the call async.

I hope something like this can get put in the README...

**Comment by tmeasday** [comment]
Hey @wizonesolutions -- are you saying that we should update the README to more firmly state that this package is a wrapper around Meteor's `HTTP` library?

I'd be very happy to accept a PR that does so ;)

**Comment by wizonesolutions** [comment]
Done! https://github.com/percolatestudio/meteor-google-api/pull/19
