### ISSUE TITLE
result.data set to null when retrieving contacts using contacts API

### ISSUE THREAD

**Issue by phsultan** [percolatestudio/meteor-google-api#22]
Hi,

I'm trying to retrieve my contacts list
```javascript
var options = {};
GoogleApi.get('m8/feeds/contacts/default/full', options, function(error, result){
          if (error) {
            console.log('error from callback : ' + error);
          } else {
            console.log('result from callback : ' + JSON.stringify(result));
          }
```

I'm not getting any error but `result` is set to `null`.

However, the following code works (adding `'alt':'json'` as a parameter) :
```javascript
var options = { 'params': {'alt': 'json'}};
GoogleApi.get('m8/feeds/contacts/default/full', options, function(error, result){
          if (error) {
            console.log('error from callback : ' + error);
          } else {
            console.log('result from callback : ' + JSON.stringify(result));
          }
```

Digging into this, I figured out that Google would send its reply with `result.data` set to `null` without this workaround, and the package passes the `result.data` to the callback after evaluating `result` (from google-api-async.js):
```javascript
      HTTP.call(method, this._host + '/' + path, options, function(error, result) {
        callback(error, result && result.data);
      });
``` 

I don't know if I did make the right API call though, any advice is welcome.

Thanks !

**Comment by tmeasday** [comment]
Hi @phsultan -- yes see this associated comment: https://github.com/percolatestudio/meteor-google-api/issues/21#issuecomment-124264237

I see a few people are running into this. I guess we might need to consider a version 2.0 of this library that more closely reflects the `HTTP` library it wraps.

**Comment by phsultan** [comment]
Yes, I'm closing this issue as there is an easy workaround anyway (adding `atl=json`to the request parameters).

Thanks !
