### ISSUE TITLE
Using Classroom API

### ISSUE THREAD

**Issue by kevster** [percolatestudio/meteor-google-api#28]
I can't seem to get Google's Classroom API to work. For example, listing a course:

https://developers.google.com/classroom/reference/rest/v1/courses/list

Gives me a 404.

Calls for doing a get request at https://classroom.googleapis.com but this plugins seems to be made only for https://www.googleapis.com . If I try sending a request to "classroom/v1/courses" (instead of using classroom as a subdomain), it also fails.

Is Classroom API out of scope for this package, or am I doing something wrong?

In advance, thanks.

**Comment by kevster** [comment]
Forked the repo to make a Classroom-version: https://github.com/kevster/meteor-google-api

**Comment by merlinpatt** [comment]
You don't have to fork the whole repo to get Classroom to work. Just add

```
Meteor.startup(function () {
  GoogleApi._host = 'https://classroom.googleapis.com/';
});
```
