### ISSUE TITLE
Error: Already registered the google OAuth service

### ISSUE THREAD

**Issue by marcoschwartz** [percolatestudio/meteor-google-api#40]
Hello,

I got the following error since updating Meteor to 1.4.3.1:

Error: Already registered the google OAuth service

I guess it's coming from the fact that Meteor now uses google-oauth and not just google, and the google module therefore is installed two times... how to fix this? Thanks!

**Comment by nunohvidal** [comment]
+1

however I got this error today when I updated Meteor to 1.4.2.7

**Comment by nunohvidal** [comment]
@marcoschwartz  I got around the issue by using a local version of the package and removing one of it's dependencies - `google`

Just add the package locally (see how below if you're not sure how to) and manually edit package.js file. What we need to change is in the call `Package.on_use` and remove `'google',` from
```
if (api.versionsFrom) {
    api.versionsFrom('0.9.0');
    api.use(['http', 'livedata', 'google', 'mrt:q@1.0.1', 'accounts-base', 'underscore']);
  }
```
in the end should look like this

```
if (api.versionsFrom) {
    api.versionsFrom('0.9.0');
    api.use(['http', 'livedata', 'mrt:q@1.0.1', 'accounts-base', 'underscore']);
  }
```

I also changed the version in `Package.describe` from `1.0.3` to `1.0.3_1` so I know for sure I'm using the local package.

To use a local version of the package, download this package ZIP and unzip it to a folder names `packages` inside the folder of your Meteor app. 
Then do the changes described above, and add the package again
`meteor add percolate:google-api`

if you changed the version as well you should get
```
meteor add percolate:google-api
percolate:google-api without a version constraint has already been added.

Changes to your project's package version selections:

google                removed from your project
percolate:google-api  upgraded from 1.0.3 to 1.0.3_1
```

**Comment by allenfuller** [comment]
I've just [submitted a pull request](https://github.com/percolatestudio/meteor-google-api/pull/41) to resolve this issue. Hopefully it works and the maintainers merge it in...

**Comment by nunohvidal** [comment]
thanks @allenfuller

**Comment by allenfuller** [comment]
Just checking in to see if anyone has heard any updates on this, or found another resolution.

**Comment by tmeasday** [comment]
Hi, we are no longer using this project, and thus it is unmaintained. Is someone interested in taking over maintenance?

**Comment by ro6** [comment]
@tmeasday I can't put a lot of time into it, but I could take over maintaining the basics, merging PRs etc...

**Comment by tmeasday** [comment]
@ro6 I'll give you GH access and permission to publish, use wisely :)

**Comment by tmeasday** [comment]
@ro6 what is your MD username?

**Comment by merlinpatt** [comment]
@tmeasday do you have a recommendation as to another library/package that we should use?

**Comment by tmeasday** [comment]
No, sorry @merlinpatt

**Comment by ro6** [comment]
@tmeasday ro6, same as GitHub

**Comment by tmeasday** [comment]
@ro6, added as a maintainer

**Comment by adamgins** [comment]
@ro6 wondering if you still planned to release your pull request?

**Comment by ro6** [comment]
@adamgins Added the fix and released. Closing this for now, please let me know if you have any issues.
