### ISSUE TITLE
exchangeRefreshToken refreshes the token for the currently logged in user regardless of supplied userId

### ISSUE THREAD

**Issue by kodie** [percolatestudio/meteor-google-api#42]
This line:
https://github.com/percolatestudio/meteor-google-api/blob/master/google-api-methods.js#L8

Changes the userId to the currently logged in user even if a different userId is supplied.

**Comment by jon-mann** [comment]
the line you referenced is nested underneath if(this.connection) which will only be true if being called from a client.  a call from a within server code can still call exchangeRefreshToken with an arbitrary userId. if this protection wasn't in place anyone could query this meteor method for an api token for any random user.
